import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-8">
    <h2
      className="font-heading mb-3"
      style={{ fontSize: "18px", color: "hsl(var(--foreground))", fontFamily: "Georgia, serif" }}
    >
      {title}
    </h2>
    <div className="space-y-3" style={{ fontSize: "14px", color: "hsl(var(--subtitle))", lineHeight: 1.75 }}>
      {children}
    </div>
  </div>
);

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background pb-16">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background border-b border-border/40 px-6 py-4 flex items-center gap-3">
        <button onClick={() => navigate(-1)} className="p-1 -ml-1" aria-label="Back">
          <ArrowLeft size={20} style={{ color: "hsl(var(--subtitle))" }} />
        </button>
        <h1
          className="font-heading"
          style={{ fontSize: "16px", color: "hsl(var(--foreground))", fontFamily: "Georgia, serif" }}
        >
          Terms of Service
        </h1>
      </div>

      <div className="max-w-xl mx-auto px-6 pt-8">
        <p
          className="italic mb-8"
          style={{ fontSize: "11px", letterSpacing: "0.1em", color: "hsl(var(--subtitle))" }}
        >
          Last updated: April 2026
        </p>

        <p className="mb-8" style={{ fontSize: "14px", color: "hsl(var(--subtitle))", lineHeight: 1.75 }}>
          Welcome to YOUtopia Within. By creating an account and using the app, you agree to these terms. Please read them — they're written to be clear, not to overwhelm you.
        </p>

        <Section title="What YOUtopia is">
          <p>YOUtopia Within is a personalised inner transformation experience that uses AI to create guided meditations and evening seeds tailored to your monthly intentions and reflections.</p>
          <p>We are currently in <strong style={{ color: "hsl(var(--foreground))" }}>free beta</strong>. Features may change, improve, or occasionally break. We appreciate your patience and feedback as we grow.</p>
        </Section>

        <Section title="Not a medical service">
          <p
            className="rounded-xl px-4 py-4"
            style={{
              background: "rgba(196, 96, 74, 0.08)",
              border: "1px solid rgba(196, 96, 74, 0.25)",
              color: "#8B3A2A",
              lineHeight: 1.8,
            }}
          >
            <strong>YOUtopia is not a medical, therapeutic, or clinical service.</strong> The meditations and content are for personal growth and wellbeing only. They are not a substitute for professional mental health care, therapy, or medical advice. If you are experiencing a mental health crisis, please contact a qualified professional or emergency services.
          </p>
        </Section>

        <Section title="Your account">
          <p>You must be 18 or older to use YOUtopia. You are responsible for keeping your login credentials secure. Please don't share your account — the experience is built for you personally.</p>
          <p>You can delete your account at any time by contacting us at <strong style={{ color: "hsl(var(--foreground))" }}>hello@youtopiawithin.com</strong>. We'll remove your data within 30 days.</p>
        </Section>

        <Section title="Your content">
          <p>The answers you provide in the intake questionnaire and the journal entries you write remain yours. You grant us a limited licence to use this content solely for the purpose of generating your personalised meditations and displaying your own reflections back to you.</p>
          <p>We will never share your personal answers or journal entries with other users or third parties, except as required to deliver the service (see our Privacy Policy).</p>
        </Section>

        <Section title="AI-generated content">
          <p>Your meditations and evening seeds are written by an AI language model (Claude by Anthropic) using the information you provide. While we carefully design the prompts and structure, the generated content is not authored by a human therapist or meditation teacher.</p>
          <p>AI content can occasionally be imperfect. If anything feels wrong or unhelpful, please let us know at <strong style={{ color: "hsl(var(--foreground))" }}>hello@youtopiawithin.com</strong>.</p>
        </Section>

        <Section title="Your voice — what we don't do">
          <p>YOUtopia never records your voice. The narration you hear in your meditations is generated by an AI text-to-speech service. You never speak into the app, and we never capture audio from your device's microphone.</p>
        </Section>

        <Section title="Intellectual property">
          <p>The YOUtopia app, its design, and all original content (excluding your personal data and AI-generated meditations) are owned by YOUtopia Within. You may not copy, reproduce, or distribute any part of the app without written permission.</p>
          <p>The personalised meditation scripts generated for you are yours to enjoy — they are not licensed for resale or redistribution.</p>
        </Section>

        <Section title="Service availability">
          <p>We aim to keep YOUtopia available at all times, but we cannot guarantee uninterrupted access. We may perform maintenance, updates, or experience downtime from third-party services. We are not liable for any loss caused by temporary unavailability.</p>
        </Section>

        <Section title="Limitation of liability">
          <p>YOUtopia Within is provided "as is" during the beta period. To the extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the app.</p>
          <p>Our total liability to you for any claim related to the service will not exceed the amount you paid us in the 12 months before the claim — which during free beta is zero.</p>
        </Section>

        <Section title="Changes to these terms">
          <p>We may update these terms as the app evolves. We'll notify you of significant changes through the app or by email. Continued use after changes constitutes acceptance.</p>
        </Section>

        <Section title="Governing law">
          <p>These terms are governed by the laws of the United Arab Emirates. Any disputes will be resolved in the courts of Dubai, UAE.</p>
        </Section>

        <Section title="Contact">
          <p>Questions? We'd love to hear from you. <strong style={{ color: "hsl(var(--foreground))" }}>hello@youtopiawithin.com</strong></p>
        </Section>
      </div>
    </div>
  );
};

export default TermsOfService;
